baseURL: "https://www.arnaudlanglade.com/"

title: "Arnaud Langlade"

enableRobotsTXT: true
summaryLength: 20
paginate: 12
imaging:
  quality: 100

defaultContentLanguage: en
languages:
  en:
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: "🇺🇸"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Training"
          url: "https://formation.arnaudlanglade.com/formation-symfony-architecture-hexagonale-ddd"
          params:
            target: "_blank"
          weight: 2
      buttons:
        - name: "Hire me"
          url: "/hire-me"
          weight: 5
          pre: "btn btn-primary text-light"
      footer:
        - name: "Training"
          url: "https://formation.arnaudlanglade.com/formation-symfony-architecture-hexagonale-ddd"
          params:
            target: "_blank"
          weight: 2

    params:
      title: "Arnaud Langlade - Technical coach and software architect"
      description: "Arnaud Langlade - With 15 years in software engineering, I’m here to help your teams grow and to build long-lasting applications as a Technical Coach and Software Architect. I have the know-how and experience to boost team efficiency and address difficult issues, ensuring your projects are both sustainable and successful."
      keywords: "arnaud langlade,langlade,freelancer,software engineer,software architect,technical coach,software craftsmanship,oop,blog,talk,tdd,bdd,ddd,event storming,example mapping,arnolanglade"
    weight: 1
  fr:
    disabled: false
    languageCode: fr
    languageDirection: ltr
    languageName: "🇨🇵"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Formation"
          url: "https://formation.arnaudlanglade.com/formation-symfony-architecture-hexagonale-ddd"
          params:
            target: "_blank"
          weight: 2
      buttons:
        - name: "Travaillons ensemble"
          url: "/hire-me"
          weight: 5
          pre: "btn btn-primary text-light"
      footer:
        - name: "Formation"
          url: "https://formation.arnaudlanglade.com/formation-symfony-architecture-hexagonale-ddd"
          params:
            target: "_blank"
          weight: 2
    params:
      title: "Arnaud Langlade - coach technique et architecte logiciel"
      description: "Arnaud Langlade - Avec 15 ans d’expérience en ingénierie logicielle, je suis là pour aider vos équipes à se développer et construire des applications durables en tant que Coach Technique et Architecte Logiciel. J’ai le savoir-faire et l’expérience nécessaires pour améliorer l’efficacité des équipes et résoudre les problèmes difficiles, assurant ainsi que vos projets soient à la fois pérennes et réussis."
      keywords: "arnaud langlade,langlade,freelance,indépendant,ingénieur logiciel,architecte logiciel,coach technique,artisan logiciel,oop,blog,conférence,tdd,bdd,ddd,event storming,example mapping,arnolanglade"
    weight: 2

params:
  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: arnolanglade
    linkedin: "https://www.linkedin.com/in/arnolanglade"
    x: "https://twitter.com/arnolanglade"
    bluesky: "https://bsky.app/profile/arnolanglade.bsky.social"
    github: "https://github.com/arnolanglade"
    mastodon: "https://mastodon.social/@arnolanglade"
    youtube: "https://www.youtube.com/@arnolanglade"
    rss: "/blog/index.xml"

  author:
    name: "Arnaud Langlade"
    email: "contact@arnaudlanglade.com"

  contact:
    - "contact@arnaudlanglade.com"

taxonomies:
  tags: "tags"

outputs:
  section:
    - html
    - rss

copyright: "© 2024 Arnaud Langlade"
