baseURL: "https://www.example.com/"
theme: "al"
languageCode: "en-us"

title: "Arnaud Langlade"

enableRobotsTXT: true
summaryLength: 20
paginate: 10

defaultContentLanguage: en
languages:
  en:
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: "🇺🇸"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Training"
          url: ""
          weight: 2
      buttons:
        - name: "Hire me"
          url: "/hire-me"
          weight: 5
          pre: "btn btn-primary text-light"
      footer:
        - name: "Training"
          url: ""
          weight: 2

    params:
      title: Arnaud Langlade - Senior software engineer, software architect, and technical coach
      description: "Arnaud Langlade - I am a software architect, and technical coach. I focus on understanding business needs to find the best solution. I love everything that ends with *DD such as DDD, BDD and TDD. These tools and all eXtreme Programming values help me to build robust and maintainable software. Last but not least, teamwork is essential: «alone we go faster, together we go further»."
      keywords: "arnaud langlade,langlade,freelancer,software engineer,software architect,technical coach,software craftsmanship,oop,blog,talk,tdd,bdd,ddd,event storming,example mapping,arnolanglade"
    weight: 1
  fr:
    disabled: false
    languageCode: fr
    languageDirection: ltr
    languageName: "🇨🇵"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Formation"
          url: ""
          weight: 2
      buttons:
        - name: "Travaillons ensemble"
          url: "/fr/travaillons-ensemble"
          weight: 5
          pre: "btn btn-primary text-light"
      footer:
        - name: "Formation"
          url: ""
          weight: 2
    params:
      title: "Arnaud Langlade - Ingénieur logiciel senior, architecte logiciel et coach technique"
      description: "Arnaud Langlade - Je suis un architecte logiciel et un coach technique. Je me concentre sur la compréhension des besoins métier pour trouver la meilleure solution. J'adore tout ce qui se termine par *DD comme DDD, BDD et TDD. Ces outils et toutes les valeurs de l'eXtreme Programming m'aident à construire des logiciels robustes et maintenables. Enfin, le travail d'équipe est essentiel : «seul nous allons plus vite, ensemble nous allons plus loin»."
      keywords: "arnaud langlade,langlade,freelancer,ingénieur logiciel,architecte logiciel,coach technique,artisan logiciel,oop,blog,conférence,tdd,bdd,ddd,event storming,example mapping,arnolanglade"
    weight: 2

params:
  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: arnolanglade
    linkedin: "https://www.linkedin.com/in/arnolanglade"
    x: "https://twitter.com/arnolanglade"
    bluesky: "https://bsky.app/profile/arnolanglade.bsky.social"
    github: "https://github.com/arnolanglade"
    mastodon: "https://www.youtube.com/@arnolanglade"
    youtube: "https://www.youtube.com/@arnolanglade"
    rss: "/blog/index.xml"

  author:
    name: "Arnaud Langlade"
    email: "contact@arnaudlanglade.com"

  contact:
    - "contact@arnaudlanglade.com"

taxonomies:
  tags: "tags"

outputs:
  section:
    - html
    - rss

copyright: "© 2024 Arnaud Langlade"
