baseURL: "https://www.example.com/"
theme: "al"
languageCode: "en-us"

title: "Arnaud Langlade"

# googleAnalytics: ""

summaryLength: 20

paginate: 1

defaultContentLanguage: en
languages:
  fr:
    disabled: false
    languageCode: fr
    languageDirection: ltr
    languageName: Français
    params:
      title: "Arnaud Langlade"
      description: "Ingéniere logiciel, formateur et conférencier"
    weight: 1
  en:
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: English
    params:
      title: "Up Business"
      description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
    weight: 2

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images:
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "#"
    twitter: "#"
    bluesky: "#"
    youtube: "#"
    mastodon: "#"

  contact:
    - "contact@arnaudlanglade.com"

  copyright: "© 2024 Arnaud Langlade"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Training"
      url: "/#"
      weight: 2

    - name: "Projects"
      url: "/projects"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 4

    - name: "Contact"
      url: "/contact"
      weight: 5

  buttons:
    - name: "Hire me"
      url: "/contact"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

    - name: "Talks"
      url: "/talks"
      weight: 3

    - name: "Training"
      url: "/#"
      weight: 4

    - name: "Projects"
      url: "/projects"
      weight: 5

    - name: "Blog"
      url: "/blog"
      weight: 6

    - name: "Contact"
      url: "/contact"
      weight: 7

taxonomies:
  series: "series"
  tags: "tags"
