baseURL: "https://www.example.com/"
theme: "al"
languageCode: "en-us"

title: "Arnaud Langlade"

# googleAnalytics: ""

summaryLength: 20

paginate: 10

defaultContentLanguage: en
languages:
  en:
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: "🇺🇸"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Home"
          url: "/#hero"
          weight: 1

        - name: "Training"
          url: ""
          weight: 2

        - name: "Projects"
          url: "/projects"
          weight: 3

        - name: "Blog"
          url: "/blog"
          weight: 4

      buttons:
        - name: "Hire me"
          url: "/contact"
          weight: 5
          pre: "btn btn-primary text-light"

      footer:
        - name: "Home"
          url: "/#hero"
          weight: 1

        - name: "About"
          url: "/about"
          weight: 2

        - name: "Talks"
          url: "/talks"
          weight: 3

        - name: "Training"
          url: ""
          weight: 4

        - name: "Projects"
          url: "/projects"
          weight: 5

        - name: "Blog"
          url: "/blog"
          weight: 6

        - name: "Contact"
          url: "/contact-me"
          weight: 7

        - name: "Newsletter"
          url: "/newsletter"
          weight: 8
    params:
      title: "Arnaud Langlade"
      description: ""
    weight: 1
  fr:
    disabled: false
    languageCode: fr
    languageDirection: ltr
    languageName: "🇨🇵"
    permalinks:
      blog: "/:title"
    menus:
      main:
        - name: "Accueil"
          url: "/fr/#hero"
          weight: 1

        - name: "Formation"
          url: ""
          weight: 2

        - name: "Projets"
          url: "/fr/projets"
          weight: 3

        - name: "Blog"
          url: "/blog"
          weight: 4

      buttons:
        - name: "Travaillons ensemble"
          url: "/contact"
          weight: 5
          pre: "btn btn-primary text-light"

      footer:
        - name: "Accueil"
          url: "/fr/#hero"
          weight: 1

        - name: "À propos"
          url: "/fr/a-propos-de-moi"
          weight: 2

        - name: "Conférences"
          url: "/fr/conferences"
          weight: 3

        - name: "Formation"
          url: ""
          weight: 4

        - name: "Projets"
          url: "/fr/projets"
          weight: 5

        - name: "Blog"
          url: "/blog"
          weight: 6

        - name: "Travaillons ensemble"
          url: "/fr/contactez-moi"
          weight: 7

        - name: "Newsletter"
          url: "/fr/newsletter"
          weight: 8
    params:
      title: "Arnaud Langlade"
      description: ""
    weight: 2

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images:
    - "images/hero-image.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "https://www.linkedin.com/in/arnolanglade"
    x: "https://twitter.com/arnolanglade"
    bluesky: "https://bsky.app/profile/arnolanglade.bsky.social"
    github: "https://github.com/arnolanglade"
    mastodon: "https://www.youtube.com/@arnolanglade"
    youtube: "https://www.youtube.com/@arnolanglade"

  contact:
    - "contact@arnaudlanglade.com"

  copyright: "© 2024 Arnaud Langlade"

taxonomies:
  series: "series"
  tags: "tags"
