[component]
structures = []
label = "Experience Card"
description = "Experience card used for testimonial lists"
icon = "wysiwyg"
tags = []

[props.testimonial-item]
name = "Hello World"
position = "Author"
blurb = "Lorem Ipsum"
image = "https://placekitten.com/1000/600"
