title: Arnaud Langlade
url: "https://arnolanglade.github.io"
plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-pagebreak

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  talks:
    output: true
    permalink: /talks/:title:output_ext
  testimonials:
    output: false
  services:
    output: false
  experiences:
    output: false
  posts:
    output: true
    permalink: /:title:output_ext

_collection_groups:
  - heading: Content
    collections:
      - pages_collection_groups
      - talks
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: talks
    values:
      layout: talk
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
