[component]
structures = []
label = "Service Card"
description = "Service card used for testimonial lists"
icon = "wysiwyg"
tags = []

[props.testimonial-item]
name = "Hello World"
position = "Author"
blurb = "Lorem Ipsum"
image = "https://placekitten.com/1000/600"
