[component]
structures = []
label = "Blog Card"
description = "Blog card used for post lists"
icon = "wysiwyg"
tags = []

[props.post]
title = "Hello World"
image = "https://placekitten.com/100/100"
url = "/"
tags = ["one", "two", "three"]
description = "Lorem Ipsum"
content = "Lorem Ipsum Donor"
date = "2018-04-24 15:01:35 +0300"
