name: Langlade Arnaud
title: Arnaud Langlade - Senior software engineer, software architect, and technical coach
description: "Arnaud Langlade - I am a software architect, and technical coach. I focus on understanding business needs to find the best solution. I love everything that ends with *DD such as DDD, BDD and TDD. These tools and all eXtreme Programming values help me to build robust and maintainable software. Last but not least, teamwork is essential: «alone we go faster, together we go further»."
keywords: "arnaud langlade,langlade,freelancer,software engineer,architect,technical coach,software,oop,blog,talk,tdd,bdd,ddd,event storming,example mapping,arnolanglade"
social_media_share_image: /images/me-home.webp
disqus-identifier: arnaudlanglade
