[component]
structures = [ "content_blocks" ]
label = "Newsletter Form"
description = "Generic newsletter form"
icon = "wysiwyg"
tags = ["Text"]

[props]
newsletter_title = "Join my mailing list"
newsletter_description = "Get inspiration, updates and, cool stuff!" # Add descriptions to the form.
newsletter_identifier = "id" # Add your MailChimp form identifier.
newsletter_button = "Subscribe"