[component]
structures = [ "content_blocks" ]
label = "Services"
description = "Service Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Happy Clients"
description_html= ""
show_testimonials = true